resources:
  - kind: CodeRepository
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: '.id | tostring'
          title: ".name"
          blueprint: '"CodeRepository"'
          properties:
            id: ".id"
            name: ".name"
            url: ".url"
            provider: ".provider"
            external_repo_id: ".external_repo_id"
            branch: ".branch"
            last_scanned_at: ".last_scanned_at"

  - kind: Vulnerability
    selector:
      query: "true"
      filter_code_repo_id: "null"
      per_page: "20"
    port:
      entity:
        mappings:
          identifier: '.id | tostring'
          title: ".title"
          blueprint: '"Vulnerability"'
          properties:
            id: ".id"
            type: ".type"
            title: ".title"
            description: ".description"
            severity_score: ".severity_score"
            severity: ".severity"
            status: ".group_status"
            time_to_fix_minutes: ".time_to_fix_minutes"
            how_to_fix: ".how_to_fix"
            cveIds: ".related_cve_ids"
      relations:
        repository: '.locations[0].id | tostring'
  - kind: User
    selector:
      query: "true"
      filter_team_id: null
      include_inactive: 0
    port:
      entity:
        mappings:
          identifier: ".id | tostring"
          title: ".full_name"
          blueprint: '"User"'
          properties:
            id: ".id"
            full_name: ".full_name"
            email: ".email"
            active: ".active"
            last_login_timestamp: ".last_login_timestamp"
            role: ".role"
            auth_type: ".auth_type"