resources:
  - kind: code_repository
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: '.id | tostring'
          title: ".name"
          blueprint: '"codeRepository"'
          properties:
            id: ".id"
            name: ".name"
            url: ".url"
            provider: ".provider"
            external_repo_id: ".external_repo_id"
            branch: ".branch"
            last_scanned_at: ".last_scanned_at"

  - kind: vulnerability
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: '.id | tostring'
          title: ".title"
          blueprint: '"vulnerability"'
          properties:
            id: ".id"
            type: ".type"
            title: ".title"
            description: ".description"
            severity_score: ".severity_score"
            severity: ".severity"
            status: ".group_status"
            time_to_fix_minutes: ".time_to_fix_minutes"
            how_to_fix: ".how_to_fix"
            cveIds: ".related_cve_ids"
      relations:
        repository: '.locations[0].id | tostring'

