resources:
  - kind: repository
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: '.id | tostring'
          title: ".name"
          blueprint: '"aikidoRepository"'
          properties:
            id: ".id"
            name: ".name"
            url: ".url"
            provider: ".provider"
            external_repo_id: ".external_repo_id"
            branch: ".branch"
            last_scanned_at: ".last_scanned_at"

  - kind: vulnerability
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: ".id | tostring"
          title: '.affected_package + " (" + .cve_id + ")"'
          blueprint: '"vulnerability"'
          properties:
            id: ".id"
            group_id: ".group_id"
            type: ".type"
            cve_id: ".cve_id"
            affected_package: ".affected_package"
            affected_file: ".affected_file"
            attack_surface: ".attack_surface"
            status: ".status"
            severity_score: ".severity_score"
            severity: ".severity"
            first_detected_at: ".first_detected_at"
            code_repo_id: ".code_repo_id"
            code_repo_name: ".code_repo_name"
      relations: { }
